runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app

handlers:
  # Handle all requests
  - url: /.*
    script: auto

env_variables:
  # Database and environment variables should be set through Google Cloud Secret Manager
  # or directly in the Google Cloud Console. These are placeholders.
  CORS_ORIGINS: '["https://feedback-mini.web.app", "http://localhost:5173", "http://localhost:3000"]'
  FRONTEND_URL: https://feedback-mini.web.app
  EMAIL_BACKEND: SMTP
  
  # NOTE: The following values should be set in Google Cloud environment
  # variables and not committed to Git:
  # - DATABASE_URL
  # - DB_USER
  # - DB_PASSWORD
  # - DB_HOST
  # - DB_PORT
  # - DB_NAME
  # - SMTP_USER
  # - SMTP_PASSWORD
  # - SECRET_KEY