runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app

env_variables:
  POSTGRES_USER: postgres
  POSTGRES_DB: feedback_db
  POSTGRES_HOST: /cloudsql/YOUR_INSTANCE_CONNECTION_NAME
  CORS_ORIGINS: https://feedback-mini.web.app,http://localhost:5173,http://localhost:3000
  FRONTEND_URL: https://feedback-mini.web.app