runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app

handlers:
  # Handle all requests
  - url: /.*
    script: auto

env_variables:
  # Full PostgreSQL connection string instead of individual components
  DATABASE_URL: "postgres://avnadmin:AVNS_wIEjTHNWLYGpcL1Rfrr@feedback-mini-app-feedback-app.b.aivencloud.com:28220/defaultdb?sslmode=require"
  CORS_ORIGINS: '["https://feedback-mini.web.app", "http://localhost:5173", "http://localhost:3000"]'
  FRONTEND_URL: https://feedback-mini.web.app
  SECRET_KEY: supersecretkey123
  EMAIL_BACKEND: SMTP